[workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "win-64"]
preview = ["pixi-build"]

[system-requirements]
cuda = "9"

[package.build]
backend = { name = "pixi-build-python", version = "*" }

[package.build.source]
git = "https://github.com/CERN/TIGRE.git"
# Note: versions prior to 3.1 are not supported due to different build system in TIGRE
rev = "d800d96a6728d33fe899fd64a0228a72b4108009"  # v3.1

[package.build.config]
# This will be default at some point, at which stage this can be removed
ignore-pypi-mapping = false
